name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: strikef/swpp202401-ci:v240419

    steps:
      - uses: actions/checkout@v3
        with:
          path: "compiler"

      - uses: actions/checkout@v3
        with:
          repository: "snu-sf-class/swpp202401-benchmarks"
          path: "benchmarks"

      - uses: actions/checkout@v3
        with:
          repository: "snu-sf-class/swpp202401-interpreter"
          path: "interpreter"

      - name: List Z3 directory structure
        run: |
          echo "Listing the contents of /opt/z3-4.13.0/"
          ls -lahR /opt/z3-4.13.0/

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git g++ cmake ninja-build re2c libhiredis-dev

      # - name: Cache Alive2 build
      #   id: cache-alive2
      #   uses: actions/cache@v3
      #   with:
      #     path: ./alive2/build
      #     key: ${{ runner.os }}-alive2-${{ hashFiles('.github/scripts/build_alive2.sh') }}

      # - if: ${{ steps.cache-alive2.outputs.cache-hit != 'true' }}
      #   name: Build Alive2
      #   run: |
      #     chmod +x compiler/.github/scripts/build_alive2.sh
      #     compiler/.github/scripts/build_alive2.sh

      - name: Configure CMake
        run: cmake -GNinja -Bbuild

      - name: Build
        run: cmake --build build --target swpp-compiler

      - name: Run unit tests
        run: ctest --test-dir build

      - name: Test Benchmark
        run: |
          chmod +x compiler/.github/scripts/test_benchmark.sh
          compiler/.github/scripts/test_benchmark.sh
