name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: strikef/swpp202401-ci:v240419

    steps:
      - uses: actions/checkout@v3
        with:
          path: "compiler"

      - uses: actions/checkout@v3
        with:
          repository: "snu-sf-class/swpp202401-benchmarks"
          path: "benchmarks"

      - uses: actions/checkout@v3
        with:
          repository: "snu-sf-class/swpp202401-interpreter"
          path: "interpreter"

      - name: Export Path
        run: |
          export PATH=/opt/cmake-3.28.3/bin:/opt/ninja-1.11.1/bin:$PATH

      - name: Install re2c
        run: apt-get update && apt-get install re2c

      - name: Cache Alive2 build
        id: cache-alive2
        uses: actions/cache@v3
        with:
          path: ./alive2/build
          key: ${{ runner.os }}-alive2-${{ hashFiles('./compiler/.github/scripts/build_alive2.sh') }}

      - if: ${{ steps.cache-alive2.outputs.cache-hit != 'true' }}
        name: Build Alive2
        run: |
          chmod +x compiler/.github/scripts/build_alive2.sh
          compiler/.github/scripts/build_alive2.sh

      - name: Configure CMake
        run: |
          cd compiler
          export PATH=/opt/cmake-3.28.3/bin:/opt/ninja-1.11.1/bin:$PATH
          cmake -GNinja -Bbuild \
            -DCMAKE_C_COMPILER=/opt/llvm-18.1.0/bin/clang \
            -DCMAKE_CXX_COMPILER=/opt/llvm-18.1.0/bin/clang++ \
            -DCMAKE_MAKE_PROGRAM=/opt/ninja-1.11.1/bin/ninja

      - name: Build
        run: |
          cd compiler
          cmake --build build --target swpp-compiler

      - name: Run unit tests
        run: |
          cd compiler
          ctest --test-dir build --rerun-failed --output-on-failure

      - name: Test Benchmark
        run: |
          chmod +x compiler/.github/scripts/test_benchmark.sh
          compiler/.github/scripts/test_benchmark.sh
